dict_generate <- function(surveyID,
                          survey_name = NULL,
                          newname = "question_name",
                          block_pattern = NULL,
                          block_sep = "_",
                          split_by_block = FALSE,
                          block = NULL,
                          reference_dict = NULL,
                          dict_diff = NULL,
                          force_level = FALSE,
                          import_id = TRUE) {
  easyname_gen <- ifelse(
    newname == "easyname",
    TRUE, FALSE
  )

  dict <- recode_json(surveyID,
    import_id = import_id,
    easyname_gen = easyname_gen,
    block_pattern = block_pattern,
    block_sep = block_sep
  )

  if (!is.null(block)) {
    dict <- dict[dict$block == block, ]
  }

  dict <- dict[c(
    "qid", newname, "block", "question",
    "item", "level", "label", "type"
  )]

  if (!is.null(survey_name)) {
    # Is it possible for a qualtrics survey to have no name in metadata?
    attr(dict, "survey_name") <- survey_name
  }

  if (!is.null(reference_dict)) {
    newname <- get_newname(reference_dict)
    # Remove qid of reference_dict, we will not use it
    # would this just be removed with contains below?
    reference_dict["qid"] <- NULL

    dict <- if (is.null(dict_diff)) {
      message("Consider using 'dict_compare' to track potential matching items")
      dict_merge(dict, reference_dict, force_level = force_level)
    } else {
      dict_merge(dict, reference_dict, dict_diff = dict_diff, force_level = force_level)
    }

    dict <- dict %>%
      # This indicator column would have been generated by dict_merge
      filter(.data[[survey_name]]) %>%
      select(
        -contains(attr(reference_dict, "survey_name")),
        -.data[[survey_name]]
      ) %>%
      rename_with(~ str_remove(., "_(.+)")) %>%
      select(
        qid, .data[[newname]],
        block, question, item,
        level, label, type
      )
  }

  # Temporary
  dict$item[dict$item == dict$question] <- NA

  attr(dict, "surveyID") <- surveyID

  if (!import_id) {
    dict$qid <- NULL
  }

  if (split_by_block) {
    dict <- split(dict, dict$block)
  }

  return(dict)
}
