dict_generate <- function(surveyID,
                          survey_name = NULL,
                          newname = "question_name",
                          split_by_block = FALSE,
                          reference_dict = NULL,
                          dict_diff = NULL,
                          import_id = TRUE) {
  easyname_gen <- ifelse(
    !is.null(reference_dict) & newname == "easyname",
    TRUE, FALSE
  )

  dict <- recode_json(surveyID, import_id = import_id, easyname_gen)
  dict <- dict[c(
    "qid", newname, "block", "question",
    "item", "level", "label", "type"
  )]

  if (!is.null(survey_name)) {
    # Is it possible for a qualtrics survey to have no name in metadata?
    attr(dict, "survey_name") <- survey_name
  }

  if (!is.null(reference_dict)) {
    # Remove qid of reference_dict, we will not use it
    # would this just be removed with contains below?
    reference_dict["qid"] <- NULL

    dict <- if (is.null(dict_diff)) {
      message("Consider using 'dict_compare' to track potential matching items")
      dict_merge(dict, reference_dict)
    } else {
      dict_merge(dict, reference_dict, dict_diff)
    }

    dict <- dict %>%
      # This indicator column would have been generated by dict_merge
      filter(.data[[survey_name]]) %>%
      select(
        -contains(attr(reference_dict, "survey_name")),
        -.data[[survey_name]]
      ) %>%
      rename_with(~ str_remove(., "_(.+)")) %>%
      select(
        qid, .data[[newname]],
        block, question, item,
        level, label, type
      )
  }

  if (!import_id) {
    dict$qid <- NULL
  }

  if (split_by_block) {
    dict <- split(dict, dict$block)
  }

  return(dict)
}
